Repository ember-codemods/ember-test-helpers-codemod, pull requests merged in 2021-03, with the labels that each got.

#43 add transform to replace deprecated this.render()
  transforms/this-render-migration/README.md
  transforms/this-render-migration/__testfixtures__/basic.input.js
  transforms/this-render-migration/__testfixtures__/basic.output.js
  transforms/this-render-migration/__testfixtures__/has-no-ember-test-helpers-import.input.js
  transforms/this-render-migration/__testfixtures__/has-no-ember-test-helpers-import.output.js
  transforms/this-render-migration/index.js
  transforms/this-render-migration/test.js
Labels: enhancement

#42 add transform for migrating deprecated ember-test-helpers API
  transforms/ember-test-helper-api-migration/README.md
  transforms/ember-test-helper-api-migration/__testfixtures__/basic.input.js
  transforms/ember-test-helper-api-migration/__testfixtures__/basic.output.js
  transforms/ember-test-helper-api-migration/__testfixtures__/do-not-have-@ember-test-helpers-import.input.js
  transforms/ember-test-helper-api-migration/__testfixtures__/do-not-have-@ember-test-helpers-import.output.js
  transforms/ember-test-helper-api-migration/__testfixtures__/do-not-have-ember-test-helpers-import.input.js
  transforms/ember-test-helper-api-migration/__testfixtures__/do-not-have-ember-test-helpers-import.output.js
  transforms/ember-test-helper-api-migration/index.js
  transforms/ember-test-helper-api-migration/test.js
Labels: enhancement

#45 Update codemod-cli and boilerplate, drop node 6 +8
  .babelrc
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .npmrc
  .prettierrc
  .travis.yml
  .yarnrc
  bin/cli.js
  package.json
  transforms/-preset.js
  transforms/acceptance/index.js
  transforms/acceptance/test.js
  transforms/acceptance/transforms/attr.js
  transforms/acceptance/transforms/click.js
  transforms/acceptance/transforms/each.js
  transforms/acceptance/transforms/fill-in.js
  transforms/acceptance/transforms/get-value.js
  transforms/acceptance/transforms/get.js
  transforms/acceptance/transforms/has-class.js
  transforms/acceptance/transforms/html.js
  transforms/acceptance/transforms/key-event.js
  transforms/acceptance/transforms/length.js
  transforms/acceptance/transforms/prop.js
  transforms/acceptance/transforms/route-helpers.js
  transforms/acceptance/transforms/tail-eq.js
  transforms/acceptance/transforms/text.js
  transforms/acceptance/transforms/trigger-event.js
  transforms/acceptance/transforms/visit.js
  transforms/ember-test-helper-api-migration/index.js
  transforms/find/index.js
  transforms/find/test.js
  transforms/integration/test.js
  transforms/integration/transforms/attr.js
  transforms/integration/transforms/click.js
  transforms/integration/transforms/each.js
  transforms/integration/transforms/focus.js
  transforms/integration/transforms/get-value.js
  transforms/integration/transforms/get.js
  transforms/integration/transforms/has-class.js
  transforms/integration/transforms/html.js
  transforms/integration/transforms/key-event.js
  transforms/integration/transforms/length.js
  transforms/integration/transforms/prop.js
  transforms/integration/transforms/set-value.js
  transforms/integration/transforms/text.js
  transforms/integration/transforms/trigger-shortcut.js
  transforms/integration/transforms/trigger.js
  transforms/native-dom/index.js
  transforms/native-dom/test.js
  transforms/this-render-migration/index.js
  transforms/utils.js
  yarn.lock
Labels: breaking, internal

#44 Setup release-it
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
